
GET  http://localhost:3000/friends
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVmMzFhZjY5LTI0NWEtNGM0Mi1iNWU0LTM0MmU3YTZiMDhkYiIsImlhdCI6MTcyNTMxNzg1MCwiZXhwIjoxNzI1OTIyNjUwfQ.jb4uysY25N-wuFw0sJmRc1m7mOO8bxInEWMykwFqFG0

###
POST  http://localhost:3000/friends
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVmMzFhZjY5LTI0NWEtNGM0Mi1iNWU0LTM0MmU3YTZiMDhkYiIsImlhdCI6MTcyNTMxNzg1MCwiZXhwIjoxNzI1OTIyNjUwfQ.jb4uysY25N-wuFw0sJmRc1m7mOO8bxInEWMykwFqFG0

{
  "email": "mary@gmail.com"
}

###
DELETE   http://localhost:3000/friends/mary@gmail.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVmMzFhZjY5LTI0NWEtNGM0Mi1iNWU0LTM0MmU3YTZiMDhkYiIsImlhdCI6MTcyNTMxNzg1MCwiZXhwIjoxNzI1OTIyNjUwfQ.jb4uysY25N-wuFw0sJmRc1m7mOO8bxInEWMykwFqFG0


###
GET   http://localhost:3000/friends/spike@gmail.com/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVmMzFhZjY5LTI0NWEtNGM0Mi1iNWU0LTM0MmU3YTZiMDhkYiIsImlhdCI6MTcyNTMxNzg1MCwiZXhwIjoxNzI1OTIyNjUwfQ.jb4uysY25N-wuFw0sJmRc1m7mOO8bxInEWMykwFqFG0

###
POST   http://localhost:3000/friends/spike@gmail.com/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVmMzFhZjY5LTI0NWEtNGM0Mi1iNWU0LTM0MmU3YTZiMDhkYiIsImlhdCI6MTcyNTMxNzg1MCwiZXhwIjoxNzI1OTIyNjUwfQ.jb4uysY25N-wuFw0sJmRc1m7mOO8bxInEWMykwFqFG0

{
  "message": "Opa"
}

