GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE5NWNhNzYxLTk1M2YtNGE4MS1hYjM3LTM1NjA1YjFlOWUwMCIsImlhdCI6MTcyMjM2MTYyMywiZXhwIjoxNzIyOTY2NDIzfQ.XrO26sBNJfakf975QqUZfrqCXOl7yFPDAUTW2D3VT1A

###

POST  http://localhost:3000/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "kaaem3332333doe@example.com",
  "password": "password123",
  "img": "default"

}

###
PATCH http://localhost:3000/users/6ebcf862-5583-43b3-a71f-1e511d7b8cf4
Content-Type: application/json

{
  "name": "John Doe hahahahha"
}

###
GET http://localhost:3000/users/6ebcf862-5583-43b3-a71f-1e511d7b8cf4
Content-Type: application/json
