GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE5NWNhNzYxLTk1M2YtNGE4MS1hYjM3LTM1NjA1YjFlOWUwMCIsImlhdCI6MTcyMjM2MTYyMywiZXhwIjoxNzIyOTY2NDIzfQ.XrO26sBNJfakf975QqUZfrqCXOl7yFPDAUTW2D3VT1A

###

POST  http://localhost:3000/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "kaaem3332333doe@example.com",
  "password": "password123",
  "img": "default"

}

###
PATCH http://localhost:3000/users/6ebcf862-5583-43b3-a71f-1e511d7b8cf4
Content-Type: application/json

{
  "name": "John Doe hahahahha"
}


###
GET http://localhost:3000/users/6ebcf862-5583-43b3-a71f-1e511d7b8cf4
Content-Type: application/json



###

POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
  "name": "Spike",
  "email": "spike@gmail.com",
  "password": "password123",
  "img": "default"

}

###
GET  http://localhost:3000/friends
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZmMwMjM1LTU2NmEtNGFmYS1iZDFlLTI5ODgwYzBhZTE2ZSIsImlhdCI6MTcyNTIxNDA0MSwiZXhwIjoxNzI1ODE4ODQxfQ.a8UtiAfceVsIIwF46shdufWxXYKJ1TkqM1_kUP1dyb8

###
POST  http://localhost:3000/friends
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZmMwMjM1LTU2NmEtNGFmYS1iZDFlLTI5ODgwYzBhZTE2ZSIsImlhdCI6MTcyNTIxNDA0MSwiZXhwIjoxNzI1ODE4ODQxfQ.a8UtiAfceVsIIwF46shdufWxXYKJ1TkqM1_kUP1dyb8

{
  "email": "spike@gmail.com"
}

###

POST  http://localhost:3000/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE5NWNhNzYxLTk1M2YtNGE4MS1hYjM3LTM1NjA1YjFlOWUwMCIsImlhdCI6MTcyNTIxMzA3NywiZXhwIjoxNzI1ODE3ODc3fQ.RATB5mUO4_RhRY8TUJH-xaxkmvdO5X8gkEIpq4S7UWw

{
  "name": "English 3"
}